apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hubble
  name: hubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubble
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hubble
    spec:
      containers:
        - image: =provider1:latest
          name: =provider1
          resources: {}
status: {}