apiVersion: v1
kind: ConfigMap
metadata:
  name: srdf-config
data:
  config.yaml: |+
    env-vars:
      active: dev
    logging:
      active: debug
      log-path: /var/log
    trace:
      enable: true
      active: datadog
      agents:
        - agent: datadog
          host: host.docker.internal
          port: 8126
    http-server:
      port: 8080
    grpc-server:
      port: 50051
      ip: "127.0.0.1"
    dev:
      database:
        name: mongodb

        db-name: serviceregistry
      event-manager:
        name: nats
        url: nats://host.docker.internal:4222
      cache:
        url: host.docker.internal:6379
        password: ""
        db: 0
    prod:
      database:
        name: documentdb
        url: "docdb-2022-01-06-05-12-54.ciba6sded7ib.us-east-2.docdb.amazonaws.com:27017"

      event-manager:
        name: nats
        url: nats://localhost:4222
---
apiVersion: v1
kind: Pod
metadata:
  name: cb-srdf
  labels:
    app: srdf
spec:
  containers:
    - name: srdf
      image: cb-srdf:1.0.1-SNAPSHOT
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: srdf-configmap
          mountPath: "/etc/config"
          readOnly: true
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 50051
          protocol: TCP
  volumes:
    - name: srdf-configmap
      configMap:
        name: srdf-config

---
apiVersion: v1
kind: Service
metadata:
  name: srdf-service
spec:
  type: NodePort
  selector:
    app: srdf
  ports:
    - protocol: TCP
      port: 8080