spring:
  cloud:
    function:
      definition: generatePDF
    stream:
      bindings:
        generatePDF-in-0:
          destination: generatePDF
#        pdfGenerated-out-0:
#          destination: invoice.pdfGenerated
#        health-out-0:
#          destination: invoice.generatePdf.health
logging:
  level:
    root: info
    org:
      springframework: info



#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: queue.log.messages
#          binder: local_rabbit
#        output:
#          destination: queue.pretty.log.messages
#          binder: local_rabbit
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: <host>
#                port: 5672
#                username: <username>
#                password: <password>
#                virtual-host: /