/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.hubble.api;

import io.hubble.model.GenerateErrorNumberResponse;
import io.hubble.model.GenerateInvoiceNumberRequest;
import io.hubble.model.GenerateInvoiceNumberResponse;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-29T12:23:50.861444+05:30[Asia/Kolkata]")
@Validated
@Api(value = "invoicenumber", description = "the invoicenumber API")
public interface InvoicenumberApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /invoicenumber
     * Generates Invoice Number Request
     *
     * @param generateInvoiceNumberRequest  (required)
     * @return Successfully generates a invoice number (status code 200)
     *         or Invalid request (status code 400)
     */

    @ApiOperation(value = "", nickname = "generateInvoiceNumber", notes = "Generates Invoice Number Request", response = GenerateInvoiceNumberResponse.class, tags={  })
    @ApiResponses(value = { 

        @ApiResponse(code = 200, message = "Successfully generates a invoice number", response = GenerateInvoiceNumberResponse.class),

        @ApiResponse(code = 400, message = "Invalid request", response = GenerateErrorNumberResponse.class) })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/invoicenumber",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<GenerateInvoiceNumberResponse> generateInvoiceNumber(

@ApiParam(value = "", required = true )   @Valid @RequestBody GenerateInvoiceNumberRequest generateInvoiceNumberRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"invoicenumber\" : \"invoicenumber\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
