openapi: '3.0.2'
info:
  title: Invoice Number Generation
  version: '1.0'
servers:
  - url: https://invoice.hubble.io/v1

paths:
  /invoicenumber:
    post:
      operationId: Generate-Invoice-Number
      description: Generates Invoice Number Request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generateInvoiceNumberRequest'
      responses:
        '200':
          description: Successfully generates a invoice number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generateInvoiceNumberResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generateErrorNumberResponse'

components:
  schemas:
    generateInvoiceNumberRequest:
      title: Generate Invoice Number Request
      type: object
      properties:
        date:
          type: string
          example: 1643434140000
        prefix:
          type: string
          example: merch
        seed:
          type: string
          example: 20
    generateInvoiceNumberResponse:
      title: Generate Invoice Number Response
      type: object
      properties:
        invoicenumber:
          type: string
    generateErrorNumberResponse:
      type: object
      title: Error Response for Generate Invoice Number
      properties:
        message:
          type: string

  
        
