@startuml
Ux:ViewPdf -> ViewPdfInvoiceAction:callLogic
ViewPdfInvoiceAction:callLogic -> Invoice:get
ViewPdfInvoiceAction:callLogic -> ViewPdfInvoiceAction:viewPdf
ViewPdfInvoiceAction:viewPdf -> InvoiceUtil.getPdfContent
InvoiceUtil.getPdfContent --> ViewPdfInvoiceAction:viewPdf
ViewPdfInvoiceAction:viewPdf --> Ux:ViewPdf
@enduml